<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\os2forms_attachment\Entity\AttachmentComponent;

/**
 * @file
 * OS2Forms Attachment functionality module.
 */

/**
 * Implements hook_webform_admin_third_party_settings_form_alter().
 */
function os2forms_attachment_webform_admin_third_party_settings_form_alter(&$form, FormStateInterface $form_state) {
  /** @var \Drupal\webform\WebformThirdPartySettingsManagerInterface $third_party_settings_manager */
  $third_party_settings_manager = \Drupal::service('webform.third_party_settings_manager');
  $template_settings = $third_party_settings_manager->getThirdPartySetting('webform_entity_print', 'template') ?: [];

  _os2forms_attachment_print_form_add_header_footer_override(
    $form['third_party_settings'],
    $template_settings
  );
}

/**
 * Implements hook_webform_third_party_settings_form_alter().
 */
function os2forms_attachment_webform_third_party_settings_form_alter(&$form, FormStateInterface $form_state) {
  /** @var \Drupal\webform\WebformInterface $webform */
  $webform = $form_state->getFormObject()->getEntity();
  $template_settings = $webform->getThirdPartySetting('webform_entity_print', 'template') ?: [];

  _os2forms_attachment_print_form_add_header_footer_override(
    $form['third_party_settings'],
    $template_settings
  );
}

/**
 * Helper function that adds header/footer override options to the forms.
 *
 * @see os2forms_attachment_webform_admin_third_party_settings_form_alter()
 * @see os2forms_attachment_webform_third_party_settings_form_alter()
 */
function _os2forms_attachment_print_form_add_header_footer_override(array &$element, array $template_settings) {
  // Getting header options.
  $header_options = [];

  $headerIds = \Drupal::entityQuery('os2forms_attachment_component')
    ->condition('type', 'header')
    ->execute();
  if (!empty($headerIds)) {
    $headers = AttachmentComponent::loadMultiple($headerIds);
    foreach ($headers as $header) {
      $header_options[$header->id()] = $header->label();
    }
  }

  // Getting footer options.
  $footer_options = [];

  $footerIds = \Drupal::entityQuery('os2forms_attachment_component')
    ->condition('type', 'footer')
    ->execute();
  if (!empty($footerIds)) {
    $footers = AttachmentComponent::loadMultiple($footerIds);
    foreach ($footers as $footer) {
      $footer_options[$footer->id()] = $footer->label();
    }
  }
  // Template.
  $template_settings += [
    'os2form_header' => '',
    'os2form_footer' => '',
  ];
  $element['webform_entity_print']['template']['os2form_header'] = array(
    '#type' => 'select',
    '#title' => t('OS2forms header override'),
    '#options' => $header_options,
    '#description' => t('Select default header that will be used on all forms (use standard for no override)'),
    '#empty_option' => t('Use standard'),
    '#default_value' => $template_settings['os2form_header'],
    '#weight' => -1,
  );

  $element['webform_entity_print']['template']['os2form_footer'] = array(
    '#type' => 'select',
    '#title' => t('OS2forms footer override'),
    '#options' => $footer_options,
    '#description' => t('Select default footer that will be used on all forms (use standard for no override)'),
    '#empty_option' => t('Use standard'),
    '#default_value' => $template_settings['os2form_footer'],
    '#weight' => 0,
  );
}

/**
 * Implements hook_webform_submission_view_alter().
 */
function os2forms_attachment_webform_submission_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  $is_entity_print = in_array($route_name, [
      'entity_print.view.debug',
      'entity_print.view'
    ])
    || \Drupal::request()->request->get('_webform_entity_print');

  if ($is_entity_print) {
    // Overriding headers and footers added by webform_entity_print.
    // @see webform_entity_print_webform_admin_third_party_settings_form_alter().

    /** @var \Drupal\webform\WebformThirdPartySettingsManagerInterface $third_party_settings_manager */
    $third_party_settings_manager = \Drupal::service('webform.third_party_settings_manager');

    $default_template_settings = $third_party_settings_manager->getThirdPartySetting('webform_entity_print', 'template') ?: [];
    $webform_template_settings = $entity->getWebform()->getThirdPartySetting('webform_entity_print', 'template') ?: [];
    $template = array_filter($webform_template_settings)
      + array_filter($default_template_settings);

    /** @var \Drupal\webform\WebformTokenManagerInterface $token_manager */
    $token_manager = \Drupal::service('webform.token_manager');

    // Header.
    if (!empty($template['os2form_header'])) {
      /** @var AttachmentComponent $header */
      $header = AttachmentComponent::load($template['os2form_header']);

      if ($header) {
        $headerBody =  $token_manager->replace($header->getBody(), $entity);

        $build['webform_entity_print_header'] = [
          '#type' => 'container',
          '#attributes' => ['class' => ['webform-entity-print-header']],
          '#markup' => $headerBody,
          '#weight' => -20,
        ];
      }
    }

    // Footer.
    if (!empty($template['os2form_footer'])) {
      /** @var AttachmentComponent $footer */
      $footer = AttachmentComponent::load($template['os2form_footer']);
      if ($footer) {
        $footerBody = $token_manager->replace($footer->getBody(), $entity);

        $build['webform_entity_print_footer'] = [
          '#type' => 'container',
          '#attributes' => ['class' => ['webform-entity-print-footer']],
          '#markup' => $footerBody,
          '#weight' => 20,
        ];
      }
    }

  }
}

/**
 * Implements hook_module_implements_alter().
 */
function os2forms_attachment_module_implements_alter(&$implementations, $hook) {
  switch ($hook) {
    // We need to move os2forms_attachment hooks after webform_entity_print
    // hook.
    // We need that for being able to overwrite default headers/footer and third
    // party settings.
    case 'webform_submission_view_alter':
    case 'webform_third_party_settings_form_alter':
    case 'webform_admin_third_party_settings_form_alter':
      $group = $implementations['os2forms_attachment'];
      unset($implementations['os2forms_attachment']);
      $implementations['os2forms_attachment'] = $group;
      break;
  }
}




