language: php

sudo: false

php:
  - 7.2

install:
  - composer global require drupal/coder
  - composer global require mglaman/drupal-check
  - composer global require friendsoftwig/twigcs
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - phpcs --config-set installed_paths ../../drupal/coder/coder_sniffer
  - phpenv rehash
  - nvm install node
  - nvm use node
  - npm install --global yarn
  - composer create-project drupal-composer/drupal-project:8.x-dev ../drupal --no-interaction
  - cd ../drupal
# See definition of variabled in Travis CI config.
#  - export REPOSITORIES='"repositories": \['
#  - export REPOSITORIES_REPLACE='"repositories": \[\{"type": "path","url": "..\/os2forms", "options": \{"symlink": false\}\},'
#  - export REQUIRE='"require": {'
#  - export REQUIRE_REPLACE='"require": {"os2forms\/os2forms": "\*",'
  - sed -i "s/$REPOSITORIES/$REPOSITORIES_REPLACE/g" composer.json
  - sed -i "s/$REQUIRE/$REQUIRE_REPLACE/g" composer.json
  - composer update
  - DRUPAL_ROOT=$(pwd)/web
  - PROJECT_PATH=$(pwd)/web/modules/contrib/os2forms
  - cd $DRUPAL_ROOT/core
  - yarn install

script:
  - phpcs --standard=Drupal --ignore=*.md $PROJECT_PATH
  - drupal-check $DRUPAL_ROOT/modules/contrib/os2forms
  - twigcs $PROJECT_PATH
  - cd $DRUPAL_ROOT/core
  - eslint $DRUPAL_ROOT/modules/contrib/os2forms
  - stylelint --aei $DRUPAL_ROOT/modules/contrib/os2forms/**/*.css
