# https://hub.docker.com/r/ddev/ddev-php-base

services:
  php:
    image: ddev/ddev-php-base:v1.24.10-old
    profiles:
      - dev
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      HOME: /tmp
      COMPOSER_HOME: /tmp/composer
      COMPOSER_CACHE_DIR: /tmp/composer-cache
    entrypoint:
      - bash
      - -lc
      - |
        git config --global --add safe.directory /app
        exec "$@"
      - bash

  markdownlint:
    image: itkdev/markdownlint
    # The default working dir is `/md`
    working_dir: /app
    volumes:
      - ./:/app
