<?php

/**
 * @file
 * OS2Forms functionality module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_entity_type_build().
 *
 * Adding os2forms_settings for to webform.
 */
function os2forms_entity_type_build(array &$entity_types) {
  $entity_types['webform']->setFormClass('os2forms_settings', 'Drupal\os2forms\Form\WebformSettingsForm');
}

/**
 * Implements hook_webform_third_party_settings_form_alter().
 */
function os2forms_webform_third_party_settings_form_alter(&$form, FormStateInterface $form_state) {
  // OS2Forms.
  $form['third_party_settings']['os2forms'] = [
    '#type' => 'details',
    '#title' => t('OS2Forms'),
    '#open' => TRUE,
    '#description' => t('OS2Forms related settings'),
  ];
}

/**
 * Implements hook_webform_admin_third_party_settings_form_alter().
 */
function os2forms_webform_admin_third_party_settings_form_alter(&$form, FormStateInterface $form_state) {
  $form['third_party_settings']['os2forms'] = [
    '#type' => 'details',
    '#title' => t('OS2Forms'),
  ];
  /** @var \Drupal\webform\WebformThirdPartySettingsManagerInterface $third_party_settings_manager */
  $third_party_settings_manager = \Drupal::service('webform.third_party_settings_manager');
  $webform_entity_storage = \Drupal::service('entity_type.manager')->getStorage('webform');

  $form['third_party_settings']['os2forms']['migrate_to_category'] = [
    '#type' => 'webform_select_other',
    '#title' => t('Migrate webforms to category'),
    '#description' => t('After migration webforms will get this category.'),
    '#options' => $webform_entity_storage->getCategories(),
    '#empty_value' => '',
    '#default_value' => $third_party_settings_manager->getThirdPartySetting('os2forms', 'migrate_to_category') ?: NULL,
  ];
}

/**
 * Implements hook_theme().
 */
function os2forms_theme() {
  return [
    'webform_handler_save_to_file_summary' => [
      'variables' => ['settings' => NULL, 'handler' => NULL],
    ],
  ];
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function os2forms_menu_local_tasks_alter(&$data, $route_name) {
  $webform = \Drupal::routeMatch()->getParameter('webform');
  $routeName = \Drupal::routeMatch()->getRouteName();
  if ($webform && $routeName == $route_name) {
    if (is_object($webform)) {
      $webform = $webform->id();
    }
    if (isset($data['tabs'][0]['entity.webform.embed']) && !\Drupal::currentUser()->hasPermission('os2forms embed webform access')) {
      unset($data['tabs'][0]['entity.webform.embed']);
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function os2forms_module_implements_alter(&$implementations, $hook) {
  switch ($hook) {
    // Move our hook_entity_type_alter() implementation to the end of the list.
    case 'menu_local_tasks_alter':
      $group = $implementations['os2forms'];
      unset($implementations['os2forms']);
      $implementations['os2forms'] = $group;
      break;
  }
}
