<?php

/**
 * @file
 * OS2Forms functionality module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_webform_third_party_settings_form_alter().
 */
function os2forms_webform_third_party_settings_form_alter(&$form, FormStateInterface $form_state) {
  // OS2Forms.
  $form['third_party_settings']['os2forms'] = [
    '#type' => 'details',
    '#title' => t('OS2Forms'),
    '#open' => TRUE,
    '#description' => t('OS2Forms related settings'),
  ];
}

/**
 * Implements hook_theme().
 */
function os2forms_theme() {
  return [
    'webform_handler_save_to_file_summary' => [
      'variables' => ['settings' => NULL, 'handler' => NULL],
    ],
  ];
}

/**
 * Implements hook_webform_migrate_d7_webform_element_ELEMENT_TYPE_alter().
 *
 * Not released hook
 * @See https://www.drupal.org/project/webform_migrate/issues/3155073
 */
function os2forms_webform_migrate_d7_webform_element_date_popup_alter(&$markup, $indent, array $element) {
  $markup .= "$indent  '#type': date\n";
  $markup .= "$indent  '#datepicker': true\n";
  $markup .= "$indent  '#date_date_format': d/m/Y\n";

  $extra = unserialize($element['extra']);
  $options = [
    'disabled',
    'readonly',
    'placehoder',
    'description',
  ];
  foreach ($options as $option) {
    if (!empty($extra[$option])) {
      $value = 'true';
      switch ($option) {
        case 'description':
        case 'placeholder':
          $value = "\"" . str_replace(['"', "\n", "\r"], ["'", '\n', ''], $extra[$option]) . "\"";
          break;
      }
      $markup .= "$indent  #$option: $value\n";
    }
  }
}
