<?php

/**
 * @file
 * This module enabled webform submission encryption as a default option.
 */

/**
 * Implements hook_webform_element_info_alter().
 *
 * Add extra processing function to "force" enabled encryption on webform
 * elements when they are being saved in the UI.
 */
function os2forms_encrypt_element_info_alter(array &$definitions): void {
  foreach ($definitions as $element_id => &$definition) {
    if ($element_id === 'webform_element_encrypt') {
      $definition['#process'][] = [
        'Drupal\os2forms_encrypt\Element\WebformElementEncrypt',
        'processWebformElementEncrypt',
      ];
    }
  }
}

/**
 * Implements hook_entity_type_alter().
 *
 * Override webform submission class to enable encryption and revision.
 */
function os2forms_encrypt_entity_type_alter(array &$entity_types): void {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  if (isset($entity_types['webform_submission'])) {
    $entity_types['webform_submission']->setStorageClass('Drupal\os2forms_encrypt\WebformOs2FormsEncryptSubmissionStorage');
  }
}

/**
 * Implements hook_webform_computed_post_save_field_alter().
 *
 * Ensure encryption of computed element values.
 */
function os2forms_encrypt_webform_computed_post_save_field_alter(array &$fields): void {
  /** @var \Drupal\os2forms_encrypt\Helper\Os2FormsEncryptor $os2formsEncryptor */
  $os2formsEncryptor = \Drupal::service('os2forms_encrypt.encryptor');

  $fields['value'] = $os2formsEncryptor->encryptValue($fields['value'], $fields['name'], $fields['webform_id']);
}
