<?php

/**
 * @file
 * Module file for os2forms_webform_maps.
 */

/**
 * Implements hook_locale_translation_projects_alter().
 */
function os2forms_webform_maps_locale_translation_projects_alter(&$projects) {
  $module_handler = \Drupal::service('module_handler');
  $path = $module_handler->getModule('os2forms_webform_maps')->getPath();
  $projects['os2forms_webform_maps']['info']['interface translation server pattern'] = $path . '/translations/%language.po';
}
