<?php

/**
 * @file
 * Install hooks for os2forms_fbs_handler.
 */

use Drupal\webform\WebformSubmissionInterface;

/**
 * Set states config to completed on existing fbs handlers.
 */
function os2forms_fbs_handler_update_10001(): void {
  // To avoid having to load full webforms we load and update webform configs.
  $configFactory = \Drupal::configFactory();

  foreach ($configFactory->listAll('webform.webform.') as $name) {
    $config = $configFactory->getEditable($name);
    $handlers = $config->get('handlers');
    if (!is_array($handlers)) {
      continue;
    }

    $changed = FALSE;

    foreach ($handlers as $handlerKey => $handler) {
      // $handler['id'] is the handler plugin id.
      if (($handler['id'] ?? NULL) !== 'os2forms_fbs') {
        continue;
      }
      $handlers[$handlerKey]['settings']['additional']['states'] = [WebformSubmissionInterface::STATE_COMPLETED];
      $changed = TRUE;
    }

    if ($changed) {
      $config->set('handlers', $handlers)->save();
    }
  }
}
