<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_webform_submission_form_alter().
 *
 * Replaces submit button title, if digital signature present.
 */
function os2forms_digital_signature_webform_submission_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\webform\WebformSubmissionInterface Interface $webformSubmission */
  $webformSubmission = $form_state->getFormObject()->getEntity();
  /** @var \Drupal\webform\WebformInterface $webform */
  $webform = $webformSubmission->getWebform();

  // Checking for os2forms_digital_signature handler presence.
  foreach ($webform->getHandlers()->getConfiguration() as $handlerConf) {
    if ($handlerConf['id'] == 'os2forms_digital_signature') {
      $config = \Drupal::config('webform.settings');
      $settings = $config->get('settings');

      // Checking if the title has not been overridden.
      if ($settings['default_submit_button_label'] == $form['actions']['submit']['#value']){
        $form['actions']['submit']['#value'] = t('Sign and submit');
      }
    }
  }
}
