#!/usr/bin/env bash
set -o errexit -o errtrace -o nounset -o pipefail
IFS=$'\n\t'

script_dir=$(pwd)

# @see https://unix.stackexchange.com/a/13474
upsearch () {
  slashes=${PWD//[^\/]/}
  directory="$PWD"
  for (( n=${#slashes}; n>0; --n ))
  do
    test -e "$directory/$1" && echo "$directory/$1" && return
    directory="$directory/.."
  done
}


# The Drupal root contains a `web` folder.
drupal_root=$(dirname "$(cd "$(upsearch web)" && pwd)")
# Module path from drupal_root (note trailing slash) (cf. https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html)
module_path=${script_dir#"${drupal_root}/"}

echo "Drupal root: $drupal_root"
echo "Module path: $module_path"

# Work around
# PHP Fatal error:  Cannot redeclare drupal_get_filename() (previously declared in /Users/rimi/ITK/github/itk-dev/os2forms_selvbetjening/web/sites/default/modules/os2forms/vendor/drupal/core/includes/bootstrap.inc:190) in /Users/rimi/ITK/github/itk-dev/os2forms_selvbetjening/web/core/includes/bootstrap.inc on line 223
# Remove our non-develop requirements and a develop dependency requiring drupal/core.
docker run --volume ${PWD}:/app --workdir /app --rm efrecon/jq:1.7 'del(.require, ."require-dev"["drupal/maillog"])' composer.json > drupal-module-code-analysis-composer.json

# It seems that the file system needs a little time to sync.
sleep 1

docker run --rm --env COMPOSER=drupal-module-code-analysis-composer.json --volume "${script_dir}":/app itkdev/php8.1-fpm:latest composer install
# Clean up
rm drupal-module-code-analysis-composer.*

# https://getcomposer.org/doc/03-cli.md#global-options
# docker run --rm --interactive --tty --volume ${drupal_root}:/app itkdev/php8.1-fpm:latest composer --working-dir $module_path code-analysis/drupal-check
docker run --rm --env PHP_MEMORY_LIMIT=-1 --interactive --tty --volume "${drupal_root}":/app itkdev/php8.1-fpm:latest composer --working-dir "$module_path" code-analysis/phpstan
