<?php

/**
 * @file
 * Install hooks for os2forms_digital_post.
 */

use Drupal\os2forms_digital_post\Helper\BeskedfordelerHelper;
use Drupal\webform\WebformSubmissionInterface;

/**
 * Implements hook_schema().
 *
 * @see BeskedfordelerHelper::schema()
 *
 * @phpstan-return array<string, mixed>
 */
function os2forms_digital_post_schema() {
  return Drupal::service(BeskedfordelerHelper::class)->schema();
}

/**
 * Install OS2Web key module.
 */
function os2forms_digital_post_update_9001(): void {
  \Drupal::service('module_installer')->install([
    'os2web_key',
  ], TRUE);
}

/**
 * Set states config to completed on existing digital post handlers.
 */
function os2forms_digital_post_update_10001(): void {
  // To avoid having to load full webforms we load and update webform configs.
  $configFactory = \Drupal::configFactory();

  foreach ($configFactory->listAll('webform.webform.') as $name) {
    $config = $configFactory->getEditable($name);
    $handlers = $config->get('handlers');
    if (!is_array($handlers)) {
      continue;
    }

    $changed = FALSE;

    foreach ($handlers as $handlerKey => $handler) {
      // $handler['id'] is the handler plugin id.
      if (($handler['id'] ?? NULL) !== 'digital_post_sf1601') {
        continue;
      }
      $handlers[$handlerKey]['settings']['additional']['states'] = [WebformSubmissionInterface::STATE_COMPLETED];
      $changed = TRUE;
    }

    if ($changed) {
      $config->set('handlers', $handlers)->save();
    }
  }
}
